#!/bin/bash

WB_EXPRESSIONS=(
write_bw

writeback:writeback_nothread
writeback:writeback_queue
writeback:writeback_exec
writeback:writeback_start
writeback:writeback_written
writeback:writeback_wait
writeback:writeback_pages_written
writeback:writeback_nowork
writeback:writeback_wake_background
writeback:writeback_wake_thread
writeback:writeback_wake_forker_thread
writeback:writeback_bdi_register
writeback:writeback_bdi_unregister
writeback:writeback_thread_start
writeback:writeback_thread_stop
writeback:wbc_writepage
writeback:writeback_queue_io
writeback:global_dirty_state
writeback:bdi_dirty_ratelimit
writeback:balance_dirty_pages
writeback:writeback_congestion_wait
writeback:writeback_wait_iff_congested
writeback:writeback_single_inode_requeue
writeback:writeback_single_inode

block:block_rq_abort
block:block_rq_requeue
block:block_rq_complete
block:block_rq_insert
block:block_rq_issue
block:block_bio_bounce
block:block_bio_complete
block:block_bio_backmerge
block:block_bio_frontmerge
block:block_bio_queue
block:block_getrq
block:block_sleeprq
block:block_plug
block:block_unplug
block:block_split
block:block_bio_remap
block:block_rq_remap

)

for e in ${WB_EXPRESSIONS[*]}
do
	./compare -e $e "$@"
	echo
done
